# Name of the workflow, displayed in the GitHub Actions tab.
name: Convert to Safari & iOS Extension

# Defines the triggers for this workflow.
on:
  # Runs on every push to the 'main' branch.
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Defines the sequence of jobs to be executed.
jobs:
  # A single job in this workflow, named 'build-and-convert'.
  build-and-convert:
    # Specifies the runner environment. macOS is required for 'xcrun'.
    runs-on: macos-latest

    # Contains the sequence of steps for this job.
    steps:
      # Step 1: Check out the repository's code so the runner can access it.
      - name: Check out the repository code
        uses: actions/checkout@v4

      # Step 2: Run the core conversion command.
      - name: Convert Chrome Extension to Safari/iOS
        run: |
          # Execute Apple's web extension converter tool.
          # The final path must point to the directory containing your manifest.json.
          xcrun safari-web-extension-converter \
            --project-location ./safari-build \
            --no-open \
            --no-prompt \
            .

      # Step 3: Upload the output as a build artifact.
      # An artifact is a file or collection of files produced during a run.
      - name: Upload the generated Xcode project
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact file that will be available for download.
          name: safari-ios-extension-project
          # The path to the folder to upload. Must match the '--project-location' argument above.
          path: ./safari-build