# Name of the workflow, displayed in the GitHub Actions tab.
name: Convert to Safari (macOS & iOS) Extension

# Defines the triggers for this workflow.
on:
  # Runs on every push to the 'master' branch.
  push:
    branches: [ safari-extension ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  convert-to-safari-extension:
    # Specifies the runner environment. macOS is required for 'xcrun'.
    runs-on: macos-latest

    # Contains the sequence of steps for this job.
    steps:
      # Step 1: Check out the repository's code so the runner can access it.
      - name: Check out the repository code
        uses: actions/checkout@v4

      # Step 2: Run the core conversion command.
      - name: Convert Chrome Extension to Safari/iOS
        run: |
          # Move WAIncognito sources to separate folder
          mkdir extension-source
          shopt -s extglob
          mv !(extension-source|.github) extension-source/
          echo "Source files moved into ./extension-source"

          # Execute Apple's web extension converter tool
          xcrun safari-web-extension-converter \
            --project-location ./safari-extension-build \
            --no-open \
            --no-prompt \
            ./extension-source
          echo "Safari Extension created in ./safari-extension-build"

      # Step 3: Upload the output as a build artifact.
      - name: Upload the generated Xcode project
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact file that will be available for download.
          name: WAIncognito-Safari-Extension
          # The paths to the folders to upload.
          path: |
            ./safari-extension-build
            ./extension-source
